Criação do front-end
Feudo-Laranja-ave-do-paraiso-DS-2021-2/copilot pull request #2
Opened 2022-03-11 22:30 UTC by marcusmartinsxx

- Foram criadas as páginas Home e Detail;
- O mapa foi inserido;
- Existe um sample text de título e subtítulo em Home;
- Os símbolos foram adicionados na FlatList.

TODO
- Organizar alinhamento dos símbolos;
- Padronizar tamanho da imagem dos símbolos;
- Redirecionar para a Detail clicando em um símbolo.

2022-03-12 21:21 UTC, Victor-oss commented
- Foram feitas duas outras telas, do perfil e dos grupos, e o menu de navegação, com os ícones, para mudar de tela. Não consegui colocar a cor laranja, fica dando um erro na variável booleana.

2022-03-14 22:34 UTC, lievertom requested changes

2022-03-14 22:34 UTC, lievertom commented on copilot/App.tsx
> +/*const TabNavigator = createBottomTabNavigator({
remover código comentado

2022-03-14 22:34 UTC, lievertom commented on copilot/package.json
> -    "@typescript-eslint/eslint-plugin": "^4.18.0",
por que foi removido o eslint de typescript?

2022-03-14 22:34 UTC, lievertom commented on copilot/src/index.tsx
> +/*const TabStack = createBottomTabNavigator()
remover código comentado

2022-03-15 04:38 UTC, marcusmartinsxx commented on copilot/package.json
> -    "@typescript-eslint/eslint-plugin": "^4.18.0",
Acho que removeu automaticamente do json, não lembro de mexermos aí.

2022-03-15 14:33 UTC, Victor-oss commented on copilot/src/index.tsx
> +/*const TabStack = createBottomTabNavigator()
Código em comentário foi removido

2022-03-15 18:13 UTC, closed without merging